### ISSUE TITLE
[AIM to Standalone] Cannot read property 'getDecorators' of undefined

### ISSUE THREAD

**Issue by ImTung** [ngneat/aim#29]
Hi!
Just try migrate my project (upgraded v14) with command: `npx @ngneat/aim-to-standalone start`
```
? Path to tsconfig file tsconfig.json
✔ Resolved dependencies and AIMs.
⠋ Refactoring to AIM...TypeError: Cannot read property 'getDecorators' of undefined
    at refactorToAim (/Users/toilatung/.npm/_npx/43192a341c0c2c44/node_modules/@ngneat/aim-to-standalone/dist/to-standalone.js:83:17)
    at Start.run (/Users/toilatung/.npm/_npx/43192a341c0c2c44/node_modules/@ngneat/aim-to-standalone/dist/commands/start/index.js:28:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Start._run (/Users/toilatung/.npm/_npx/43192a341c0c2c44/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/Users/toilatung/.npm/_npx/43192a341c0c2c44/node_modules/@oclif/core/lib/config/config.js:268:25)
    at async Object.run (/Users/toilatung/.npm/_npx/43192a341c0c2c44/node_modules/@oclif/core/lib/main.js:73:5)
⠼ Refactoring to AIM...
```
and it's still refactoring...
any ideas to make it work?
thank you 🙏

**Comment by NetanelBasal** [comment]
Can you please change the source code to, and add the output here:
```ts
  const relatedClassDec = aimModule.sourceFile
                .getClasses()
                .find((d) => d.getName() === relatedClassName)

if(!relatedClassDec) {
	console.log( aimModule.sourceFile.getText())
        return;
}
```

**Comment by NetanelBasal** [comment]
The component is not on the same file as the module?

**Comment by NetanelBasal** [comment]
Anyway, it should be in the same file. I'll add protection for this. Does the rest seem to work fine?

**Comment by NetanelBasal** [comment]
Fixed in latest version.
